setup: &setup
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  admins:
    - davetoxa

development:
  <<: *setup

test:
  <<: *setup
  secret_token: test
  secret_key_base: test

production:
  <<: *setup
